name: jerawat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^4.0.0
  image_picker: ^0.8.8
  tflite_flutter: ^0.10.1

  flutter: 
    sdk: flutter
  firebase_core: ^2.13.1
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.8.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/icon/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
  uses-material-design: true

